"""create trend table

Revision ID: 30298a50b4ac
Revises: 
Create Date: 2022-07-12 13:31:32.550480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30298a50b4ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trend', 'ranking',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trend', 'ranking',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
